//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    using System.Reflection;
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.Diagnostics.CodeAnalysis;
    
    
    [ExcludeFromCodeCoverageAttribute()]
    public class bet_Earningstatement : Entity {
        
        public new const string EntityLogicalName = "bet_earningstatement";
        
        public new const string EntitySetName = "bet_earningstatements";
        
        public new const string PrimaryIdAttribute = "bet_earningstatementid";
        
        public bet_Earningstatement() {
        }
        
        public bet_Earningstatement(ExpandoObject expandoObject) : 
                base(expandoObject) {
        }
        
        public DateTime? bet_Approvaldate {
            get {
                return this.GetAttributeValue<DateTime?>("bet_Approvaldate");
            }
            set {
                this.SetAttributeValue("bet_Approvaldate", value);
            }
        }
        
        [OnlyDate()]
        public DateTime? bet_Datefrom {
            get {
                return this.GetAttributeValue<DateTime?>("bet_Datefrom");
            }
            set {
                this.SetAttributeValue("bet_Datefrom", value);
            }
        }
        
        [OnlyDate()]
        public DateTime? bet_Dateto {
            get {
                return this.GetAttributeValue<DateTime?>("bet_Dateto");
            }
            set {
                this.SetAttributeValue("bet_Dateto", value);
            }
        }
        
        public int? bet_Dayspermonth {
            get {
                return this.GetAttributeValue<int?>("bet_Dayspermonth");
            }
            set {
                this.SetAttributeValue("bet_Dayspermonth", value);
            }
        }
        
        public int? bet_Defaultdimension {
            get {
                return this.GetAttributeValue<int?>("bet_Defaultdimension");
            }
            set {
                this.SetAttributeValue("bet_Defaultdimension", value);
            }
        }
        
        public DateTime? bet_del_Datefrom {
            get {
                return this.GetAttributeValue<DateTime?>("bet_del_Datefrom");
            }
            set {
                this.SetAttributeValue("bet_del_Datefrom", value);
            }
        }
        
        public DateTime? bet_del_Dateto {
            get {
                return this.GetAttributeValue<DateTime?>("bet_del_Dateto");
            }
            set {
                this.SetAttributeValue("bet_del_Dateto", value);
            }
        }
        
        // <summary>
        // Required name field
        // </summary>
        public String bet_Document {
            get {
                return this.GetAttributeValue<String>("bet_Document");
            }
            set {
                this.SetAttributeValue("bet_Document", value);
            }
        }
        
        [EntityReference("bet_earningstatementevals", "_bet_earningstatementeval_value")]
        public EntityReference bet_Earningstatementeval {
            get {
                return this.GetAttributeValue<EntityReference>("bet_Earningstatementeval@odata.bind");
            }
            set {
                this.SetAttributeValue("bet_Earningstatementeval@odata.bind", value);
            }
        }
        
        [Entity("bet_earningstatementeval", "bet_Earningstatementeval")]
        public bet_Earningstatementeval bet_EarningstatementevalEntity {
            get {
                return this.GetAttributeValue<bet_Earningstatementeval>("bet_Earningstatementeval");
            }
            set {
                this.SetAttributeValue("bet_Earningstatementeval", value);
            }
        }
        
        // <summary>
        // Unique identifier for entity instances
        // </summary>
        public Guid? bet_EarningstatementId {
            get {
                return this.GetAttributeValue<Guid?>("bet_EarningstatementId");
            }
            set {
                this.SetAttributeValue("bet_EarningstatementId", value);
            }
        }
        
        public int? bet_Employment {
            get {
                return this.GetAttributeValue<int?>("bet_Employment");
            }
            set {
                this.SetAttributeValue("bet_Employment", value);
            }
        }
        
        public decimal? bet_Hoursperday {
            get {
                return this.GetAttributeValue<decimal?>("bet_Hoursperday");
            }
            set {
                this.SetAttributeValue("bet_Hoursperday", value);
            }
        }
        
        // <summary>
        // from 0 to 31*24=744
        // </summary>
        public decimal? bet_Hourspermonth {
            get {
                return this.GetAttributeValue<decimal?>("bet_Hourspermonth");
            }
            set {
                this.SetAttributeValue("bet_Hourspermonth", value);
            }
        }
        
        public int? bet_OMoperatingunitarea {
            get {
                return this.GetAttributeValue<int?>("bet_OMoperatingunitarea");
            }
            set {
                this.SetAttributeValue("bet_OMoperatingunitarea", value);
            }
        }
        
        public int? bet_OMoperatingunitcostcenter {
            get {
                return this.GetAttributeValue<int?>("bet_OMoperatingunitcostcenter");
            }
            set {
                this.SetAttributeValue("bet_OMoperatingunitcostcenter", value);
            }
        }
        
        public int? bet_OMoperatingunitdepartment {
            get {
                return this.GetAttributeValue<int?>("bet_OMoperatingunitdepartment");
            }
            set {
                this.SetAttributeValue("bet_OMoperatingunitdepartment", value);
            }
        }
        
        public String bet_Period {
            get {
                return this.GetAttributeValue<String>("bet_Period");
            }
            set {
                this.SetAttributeValue("bet_Period", value);
            }
        }
        
        public bool? bet_Processmanual {
            get {
                return this.GetAttributeValue<bool?>("bet_Processmanual");
            }
            set {
                this.SetAttributeValue("bet_Processmanual", value);
            }
        }
        
        public int? bet_Statementeval {
            get {
                return this.GetAttributeValue<int?>("bet_Statementeval");
            }
            set {
                this.SetAttributeValue("bet_Statementeval", value);
            }
        }
        
        public int? bet_Status {
            get {
                return this.GetAttributeValue<int?>("bet_Status");
            }
            set {
                this.SetAttributeValue("bet_Status", value);
            }
        }
        
        public int? bet_Worker {
            get {
                return this.GetAttributeValue<int?>("bet_Worker");
            }
            set {
                this.SetAttributeValue("bet_Worker", value);
            }
        }
        
        // <summary>
        // Unique identifier of the user who created the record.
        // </summary>
        [EntityReference("systemusers", "_createdby_value")]
        public EntityReference CreatedBy {
            get {
                return this.GetAttributeValue<EntityReference>("createdby@odata.bind");
            }
            set {
                this.SetAttributeValue("createdby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time when the record was created.
        // </summary>
        public DateTime? CreatedOn {
            get {
                return this.GetAttributeValue<DateTime?>("CreatedOn");
            }
            set {
                this.SetAttributeValue("CreatedOn", value);
            }
        }
        
        // <summary>
        // Unique identifier of the delegate user who created the record.
        // </summary>
        [EntityReference("systemusers", "_createdonbehalfby_value")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return this.GetAttributeValue<EntityReference>("createdonbehalfby@odata.bind");
            }
            set {
                this.SetAttributeValue("createdonbehalfby@odata.bind", value);
            }
        }
        
        // <summary>
        // Sequence number of the import that created this record.
        // </summary>
        public int? ImportSequenceNumber {
            get {
                return this.GetAttributeValue<int?>("ImportSequenceNumber");
            }
            set {
                this.SetAttributeValue("ImportSequenceNumber", value);
            }
        }
        
        // <summary>
        // Unique identifier of the user who modified the record.
        // </summary>
        [EntityReference("systemusers", "_modifiedby_value")]
        public EntityReference ModifiedBy {
            get {
                return this.GetAttributeValue<EntityReference>("modifiedby@odata.bind");
            }
            set {
                this.SetAttributeValue("modifiedby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time when the record was modified.
        // </summary>
        public DateTime? ModifiedOn {
            get {
                return this.GetAttributeValue<DateTime?>("ModifiedOn");
            }
            set {
                this.SetAttributeValue("ModifiedOn", value);
            }
        }
        
        // <summary>
        // Unique identifier of the delegate user who modified the record.
        // </summary>
        [EntityReference("systemusers", "_modifiedonbehalfby_value")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return this.GetAttributeValue<EntityReference>("modifiedonbehalfby@odata.bind");
            }
            set {
                this.SetAttributeValue("modifiedonbehalfby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time that the record was migrated.
        // </summary>
        [OnlyDate()]
        public DateTime? OverriddenCreatedOn {
            get {
                return this.GetAttributeValue<DateTime?>("OverriddenCreatedOn");
            }
            set {
                this.SetAttributeValue("OverriddenCreatedOn", value);
            }
        }
        
        // <summary>
        // Owner Id
        // </summary>
        [EntityReference("systemusers", "_ownerid_value")]
        public EntityReference OwnerId {
            get {
                return this.GetAttributeValue<EntityReference>("OwnerId@odata.bind");
            }
            set {
                this.SetAttributeValue("OwnerId@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the business unit that owns the record
        // </summary>
        [EntityReference("businessunits", "_owningbusinessunit_value")]
        public EntityReference OwningBusinessUnit {
            get {
                return this.GetAttributeValue<EntityReference>("owningbusinessunit@odata.bind");
            }
            set {
                this.SetAttributeValue("owningbusinessunit@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the team that owns the record.
        // </summary>
        [EntityReference("teams", "_owningteam_value")]
        public EntityReference OwningTeam {
            get {
                return this.GetAttributeValue<EntityReference>("owningteam@odata.bind");
            }
            set {
                this.SetAttributeValue("owningteam@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the user that owns the record.
        // </summary>
        [EntityReference("systemusers", "_owninguser_value")]
        public EntityReference OwningUser {
            get {
                return this.GetAttributeValue<EntityReference>("owninguser@odata.bind");
            }
            set {
                this.SetAttributeValue("owninguser@odata.bind", value);
            }
        }
        
        // <summary>
        // Status of the Earning statement
        // </summary>
        public int? statecode {
            get {
                return this.GetAttributeValue<int?>("statecode");
            }
            set {
                this.SetAttributeValue("statecode", value);
            }
        }
        
        // <summary>
        // Reason for the status of the Earning statement
        // </summary>
        public int? statuscode {
            get {
                return this.GetAttributeValue<int?>("statuscode");
            }
            set {
                this.SetAttributeValue("statuscode", value);
            }
        }
        
        // <summary>
        // For internal use only.
        // </summary>
        public int? TimeZoneRuleVersionNumber {
            get {
                return this.GetAttributeValue<int?>("TimeZoneRuleVersionNumber");
            }
            set {
                this.SetAttributeValue("TimeZoneRuleVersionNumber", value);
            }
        }
        
        // <summary>
        // Time zone code that was in use when the record was created.
        // </summary>
        public int? UTCConversionTimeZoneCode {
            get {
                return this.GetAttributeValue<int?>("UTCConversionTimeZoneCode");
            }
            set {
                this.SetAttributeValue("UTCConversionTimeZoneCode", value);
            }
        }
        
        // <summary>
        // Version Number
        // </summary>
        public long? VersionNumber {
            get {
                return this.GetAttributeValue<long?>("VersionNumber");
            }
            set {
                this.SetAttributeValue("VersionNumber", value);
            }
        }
        
        public class Fields {
            
            public const string _bet_Earningstatementeval_value = "_bet_earningstatementeval_value";
            
            public const string _CreatedBy_value = "_createdby_value";
            
            public const string _CreatedOnBehalfBy_value = "_createdonbehalfby_value";
            
            public const string _ModifiedBy_value = "_modifiedby_value";
            
            public const string _ModifiedOnBehalfBy_value = "_modifiedonbehalfby_value";
            
            public const string _OwnerId_value = "_ownerid_value";
            
            public const string _OwningBusinessUnit_value = "_owningbusinessunit_value";
            
            public const string _OwningTeam_value = "_owningteam_value";
            
            public const string _OwningUser_value = "_owninguser_value";
            
            public const string bet_Approvaldate = "bet_approvaldate";
            
            public const string bet_Datefrom = "bet_datefrom";
            
            public const string bet_Dateto = "bet_dateto";
            
            public const string bet_Dayspermonth = "bet_dayspermonth";
            
            public const string bet_Defaultdimension = "bet_defaultdimension";
            
            public const string bet_del_Datefrom = "bet_del_datefrom";
            
            public const string bet_del_Dateto = "bet_del_dateto";
            
            public const string bet_Document = "bet_document";
            
            public const string bet_Earningstatementeval = "bet_earningstatementeval";
            
            public const string bet_EarningstatementevalName = "bet_earningstatementevalname";
            
            public const string bet_EarningstatementId = "bet_earningstatementid";
            
            public const string bet_Employment = "bet_employment";
            
            public const string bet_Hoursperday = "bet_hoursperday";
            
            public const string bet_Hourspermonth = "bet_hourspermonth";
            
            public const string bet_OMoperatingunitarea = "bet_omoperatingunitarea";
            
            public const string bet_OMoperatingunitcostcenter = "bet_omoperatingunitcostcenter";
            
            public const string bet_OMoperatingunitdepartment = "bet_omoperatingunitdepartment";
            
            public const string bet_Period = "bet_period";
            
            public const string bet_Processmanual = "bet_processmanual";
            
            public const string bet_processmanualName = "bet_processmanualname";
            
            public const string bet_Statementeval = "bet_statementeval";
            
            public const string bet_Status = "bet_status";
            
            public const string bet_statusName = "bet_statusname";
            
            public const string bet_Worker = "bet_worker";
            
            public const string CreatedBy = "createdby";
            
            public const string CreatedByName = "createdbyname";
            
            public const string CreatedByYomiName = "createdbyyominame";
            
            public const string CreatedOn = "createdon";
            
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            
            public const string CreatedOnBehalfByName = "createdonbehalfbyname";
            
            public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
            
            public const string ImportSequenceNumber = "importsequencenumber";
            
            public const string ModifiedBy = "modifiedby";
            
            public const string ModifiedByName = "modifiedbyname";
            
            public const string ModifiedByYomiName = "modifiedbyyominame";
            
            public const string ModifiedOn = "modifiedon";
            
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            
            public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
            
            public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
            
            public const string OverriddenCreatedOn = "overriddencreatedon";
            
            public const string OwnerId = "ownerid";
            
            public const string OwnerIdName = "owneridname";
            
            public const string OwnerIdType = "owneridtype";
            
            public const string OwnerIdYomiName = "owneridyominame";
            
            public const string OwningBusinessUnit = "owningbusinessunit";
            
            public const string OwningTeam = "owningteam";
            
            public const string OwningUser = "owninguser";
            
            public const string statecode = "statecode";
            
            public const string statecodeName = "statecodename";
            
            public const string statuscode = "statuscode";
            
            public const string statuscodeName = "statuscodename";
            
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
            
            public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
            
            public const string VersionNumber = "versionnumber";
            
            public const string Id = "bet_earningstatementid";
        }
        
        public class Properties {
            
            public const string bet_Earningstatementeval = "bet_Earningstatementeval";
            
            public const string createdby = "createdby";
            
            public const string createdonbehalfby = "createdonbehalfby";
            
            public const string modifiedby = "modifiedby";
            
            public const string modifiedonbehalfby = "modifiedonbehalfby";
            
            public const string ownerid = "ownerid";
            
            public const string owningbusinessunit = "owningbusinessunit";
            
            public const string owningteam = "owningteam";
            
            public const string owninguser = "owninguser";
        }
        
        public class Schemas {
            
            public const string bet_Approvaldate = "bet_Approvaldate";
            
            public const string bet_Datefrom = "bet_Datefrom";
            
            public const string bet_Dateto = "bet_Dateto";
            
            public const string bet_Dayspermonth = "bet_Dayspermonth";
            
            public const string bet_Defaultdimension = "bet_Defaultdimension";
            
            public const string bet_del_Datefrom = "bet_del_Datefrom";
            
            public const string bet_del_Dateto = "bet_del_Dateto";
            
            public const string bet_Document = "bet_Document";
            
            public const string bet_Earningstatementeval = "bet_Earningstatementeval";
            
            public const string bet_EarningstatementevalName = "bet_EarningstatementevalName";
            
            public const string bet_EarningstatementId = "bet_EarningstatementId";
            
            public const string bet_Employment = "bet_Employment";
            
            public const string bet_Hoursperday = "bet_Hoursperday";
            
            public const string bet_Hourspermonth = "bet_Hourspermonth";
            
            public const string bet_OMoperatingunitarea = "bet_OMoperatingunitarea";
            
            public const string bet_OMoperatingunitcostcenter = "bet_OMoperatingunitcostcenter";
            
            public const string bet_OMoperatingunitdepartment = "bet_OMoperatingunitdepartment";
            
            public const string bet_Period = "bet_Period";
            
            public const string bet_Processmanual = "bet_Processmanual";
            
            public const string bet_processmanualName = "bet_processmanualName";
            
            public const string bet_Statementeval = "bet_Statementeval";
            
            public const string bet_Status = "bet_Status";
            
            public const string bet_statusName = "bet_statusName";
            
            public const string bet_Worker = "bet_Worker";
            
            public const string CreatedBy = "CreatedBy";
            
            public const string CreatedByName = "CreatedByName";
            
            public const string CreatedByYomiName = "CreatedByYomiName";
            
            public const string CreatedOn = "CreatedOn";
            
            public const string CreatedOnBehalfBy = "CreatedOnBehalfBy";
            
            public const string CreatedOnBehalfByName = "CreatedOnBehalfByName";
            
            public const string CreatedOnBehalfByYomiName = "CreatedOnBehalfByYomiName";
            
            public const string ImportSequenceNumber = "ImportSequenceNumber";
            
            public const string ModifiedBy = "ModifiedBy";
            
            public const string ModifiedByName = "ModifiedByName";
            
            public const string ModifiedByYomiName = "ModifiedByYomiName";
            
            public const string ModifiedOn = "ModifiedOn";
            
            public const string ModifiedOnBehalfBy = "ModifiedOnBehalfBy";
            
            public const string ModifiedOnBehalfByName = "ModifiedOnBehalfByName";
            
            public const string ModifiedOnBehalfByYomiName = "ModifiedOnBehalfByYomiName";
            
            public const string OverriddenCreatedOn = "OverriddenCreatedOn";
            
            public const string OwnerId = "OwnerId";
            
            public const string OwnerIdName = "OwnerIdName";
            
            public const string OwnerIdType = "OwnerIdType";
            
            public const string OwnerIdYomiName = "OwnerIdYomiName";
            
            public const string OwningBusinessUnit = "OwningBusinessUnit";
            
            public const string OwningTeam = "OwningTeam";
            
            public const string OwningUser = "OwningUser";
            
            public const string statecode = "statecode";
            
            public const string statecodeName = "statecodeName";
            
            public const string statuscode = "statuscode";
            
            public const string statuscodeName = "statuscodeName";
            
            public const string TimeZoneRuleVersionNumber = "TimeZoneRuleVersionNumber";
            
            public const string UTCConversionTimeZoneCode = "UTCConversionTimeZoneCode";
            
            public const string VersionNumber = "VersionNumber";
        }
    }
}
