//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    using System.Reflection;
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.Diagnostics.CodeAnalysis;
    
    
    [ExcludeFromCodeCoverageAttribute()]
    public class cdm_employment : Entity {
        
        public new const string EntityLogicalName = "cdm_employment";
        
        public new const string EntitySetName = "cdm_employments";
        
        public new const string PrimaryIdAttribute = "cdm_employmentid";
        
        public cdm_employment() {
        }
        
        public cdm_employment(ExpandoObject expandoObject) : 
                base(expandoObject) {
        }
        
        // <summary>
        // The date and time the worker starts the employment adjusted from the original.
        // </summary>
        public DateTime? cdm_AdjustedWorkerStartDate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_AdjustedWorkerStartDate");
            }
            set {
                this.SetAttributeValue("cdm_AdjustedWorkerStartDate", value);
            }
        }
        
        // <summary>
        // The legal entity of the employment.
        // </summary>
        [EntityReference("cdm_companies", "_cdm_companyid_value")]
        public EntityReference cdm_CompanyId {
            get {
                return this.GetAttributeValue<EntityReference>("cdm_CompanyId@odata.bind");
            }
            set {
                this.SetAttributeValue("cdm_CompanyId@odata.bind", value);
            }
        }
        
        // <summary>
        // The display value of the dimensions set on the employment.
        // </summary>
        public String cdm_DimensionDisplayValue {
            get {
                return this.GetAttributeValue<String>("cdm_DimensionDisplayValue");
            }
            set {
                this.SetAttributeValue("cdm_DimensionDisplayValue", value);
            }
        }
        
        // <summary>
        // The amount of lead time the employer needs before a transition.  Example:  1, 2, 3 etc
        // </summary>
        public decimal? cdm_EmployerNoticeAmount {
            get {
                return this.GetAttributeValue<decimal?>("cdm_EmployerNoticeAmount");
            }
            set {
                this.SetAttributeValue("cdm_EmployerNoticeAmount", value);
            }
        }
        
        // <summary>
        // The unit of time for notice of a change in employment provided by the employer  Example:  Day or week
        // </summary>
        public int? cdm_EmployerUnitofNotice {
            get {
                return this.GetAttributeValue<int?>("cdm_EmployerUnitofNotice");
            }
            set {
                this.SetAttributeValue("cdm_EmployerUnitofNotice", value);
            }
        }
        
        // <summary>
        // The date and time the employment ends.
        // </summary>
        public DateTime? cdm_EmploymentEndDate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_EmploymentEndDate");
            }
            set {
                this.SetAttributeValue("cdm_EmploymentEndDate", value);
            }
        }
        
        // <summary>
        // Unique identifier for entity instances
        // </summary>
        public Guid? cdm_employmentId {
            get {
                return this.GetAttributeValue<Guid?>("cdm_employmentId");
            }
            set {
                this.SetAttributeValue("cdm_employmentId", value);
            }
        }
        
        // <summary>
        // The number of the employment.
        // </summary>
        public String cdm_EmploymentNumber {
            get {
                return this.GetAttributeValue<String>("cdm_EmploymentNumber");
            }
            set {
                this.SetAttributeValue("cdm_EmploymentNumber", value);
            }
        }
        
        // <summary>
        // The date and time the employment begins.
        // </summary>
        public DateTime? cdm_EmploymentStartDate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_EmploymentStartDate");
            }
            set {
                this.SetAttributeValue("cdm_EmploymentStartDate", value);
            }
        }
        
        // <summary>
        // The date and time the worker last worked.
        // </summary>
        public DateTime? cdm_LastDateWorked {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_LastDateWorked");
            }
            set {
                this.SetAttributeValue("cdm_LastDateWorked", value);
            }
        }
        
        // <summary>
        // The probation date for the worker
        // </summary>
        public DateTime? cdm_probationenddate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_probationenddate");
            }
            set {
                this.SetAttributeValue("cdm_probationenddate", value);
            }
        }
        
        // <summary>
        // The date and time the employment was terminated.
        // </summary>
        public DateTime? cdm_TransitionDate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_TransitionDate");
            }
            set {
                this.SetAttributeValue("cdm_TransitionDate", value);
            }
        }
        
        // <summary>
        // Reason code for employment termination
        // </summary>
        [EntityReference("cdm_reasoncodes", "_cdm_transitionreasoncode_value")]
        public EntityReference cdm_transitionreasoncode {
            get {
                return this.GetAttributeValue<EntityReference>("cdm_transitionreasoncode@odata.bind");
            }
            set {
                this.SetAttributeValue("cdm_transitionreasoncode@odata.bind", value);
            }
        }
        
        // <summary>
        // The date and time the employment is valid.
        // </summary>
        public DateTime? cdm_ValidFrom {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_ValidFrom");
            }
            set {
                this.SetAttributeValue("cdm_ValidFrom", value);
            }
        }
        
        // <summary>
        // The date and time to which the employment is valid.
        // </summary>
        public DateTime? cdm_ValidTo {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_ValidTo");
            }
            set {
                this.SetAttributeValue("cdm_ValidTo", value);
            }
        }
        
        // <summary>
        // The worker that is associated with the employment
        // </summary>
        [EntityReference("cdm_workers", "_cdm_workerid_value")]
        public EntityReference cdm_WorkerId {
            get {
                return this.GetAttributeValue<EntityReference>("cdm_WorkerId@odata.bind");
            }
            set {
                this.SetAttributeValue("cdm_WorkerId@odata.bind", value);
            }
        }
        
        // <summary>
        // The worker that is associated with the employment
        // </summary>
        [Entity("cdm_worker", "cdm_WorkerId")]
        public cdm_worker cdm_WorkerIdEntity {
            get {
                return this.GetAttributeValue<cdm_worker>("cdm_WorkerId");
            }
            set {
                this.SetAttributeValue("cdm_WorkerId", value);
            }
        }
        
        // <summary>
        // The minimum amount of notice a worker is required to give for an upcoming transition  Example: 1, 2, 3 etc
        // </summary>
        public decimal? cdm_WorkerNoticeAmount {
            get {
                return this.GetAttributeValue<decimal?>("cdm_WorkerNoticeAmount");
            }
            set {
                this.SetAttributeValue("cdm_WorkerNoticeAmount", value);
            }
        }
        
        // <summary>
        // The date and time the worker starts the employment.
        // </summary>
        public DateTime? cdm_WorkerStartDate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_WorkerStartDate");
            }
            set {
                this.SetAttributeValue("cdm_WorkerStartDate", value);
            }
        }
        
        // <summary>
        // The type of employment held by the worker  Example:   Employee, Contractor, Volunteer
        // </summary>
        public int? cdm_WorkerType {
            get {
                return this.GetAttributeValue<int?>("cdm_WorkerType");
            }
            set {
                this.SetAttributeValue("cdm_WorkerType", value);
            }
        }
        
        // <summary>
        // The unit of time for notice of a change in employment provided by the worker  Example:  Day or week
        // </summary>
        public int? cdm_WorkerUnitofNotice {
            get {
                return this.GetAttributeValue<int?>("cdm_WorkerUnitofNotice");
            }
            set {
                this.SetAttributeValue("cdm_WorkerUnitofNotice", value);
            }
        }
        
        // <summary>
        // Unique identifier of the user who created the record.
        // </summary>
        [EntityReference("systemusers", "_createdby_value")]
        public EntityReference CreatedBy {
            get {
                return this.GetAttributeValue<EntityReference>("createdby@odata.bind");
            }
            set {
                this.SetAttributeValue("createdby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time when the record was created.
        // </summary>
        public DateTime? CreatedOn {
            get {
                return this.GetAttributeValue<DateTime?>("CreatedOn");
            }
            set {
                this.SetAttributeValue("CreatedOn", value);
            }
        }
        
        // <summary>
        // Unique identifier of the delegate user who created the record.
        // </summary>
        [EntityReference("systemusers", "_createdonbehalfby_value")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return this.GetAttributeValue<EntityReference>("createdonbehalfby@odata.bind");
            }
            set {
                this.SetAttributeValue("createdonbehalfby@odata.bind", value);
            }
        }
        
        // <summary>
        // Sequence number of the import that created this record.
        // </summary>
        public int? ImportSequenceNumber {
            get {
                return this.GetAttributeValue<int?>("ImportSequenceNumber");
            }
            set {
                this.SetAttributeValue("ImportSequenceNumber", value);
            }
        }
        
        // <summary>
        // Unique identifier of the user who modified the record.
        // </summary>
        [EntityReference("systemusers", "_modifiedby_value")]
        public EntityReference ModifiedBy {
            get {
                return this.GetAttributeValue<EntityReference>("modifiedby@odata.bind");
            }
            set {
                this.SetAttributeValue("modifiedby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time when the record was modified.
        // </summary>
        public DateTime? ModifiedOn {
            get {
                return this.GetAttributeValue<DateTime?>("ModifiedOn");
            }
            set {
                this.SetAttributeValue("ModifiedOn", value);
            }
        }
        
        // <summary>
        // Unique identifier of the delegate user who modified the record.
        // </summary>
        [EntityReference("systemusers", "_modifiedonbehalfby_value")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return this.GetAttributeValue<EntityReference>("modifiedonbehalfby@odata.bind");
            }
            set {
                this.SetAttributeValue("modifiedonbehalfby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time that the record was migrated.
        // </summary>
        [OnlyDate()]
        public DateTime? OverriddenCreatedOn {
            get {
                return this.GetAttributeValue<DateTime?>("OverriddenCreatedOn");
            }
            set {
                this.SetAttributeValue("OverriddenCreatedOn", value);
            }
        }
        
        // <summary>
        // Owner Id
        // </summary>
        [EntityReference("systemusers", "_ownerid_value")]
        public EntityReference OwnerId {
            get {
                return this.GetAttributeValue<EntityReference>("OwnerId@odata.bind");
            }
            set {
                this.SetAttributeValue("OwnerId@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the business unit that owns the record
        // </summary>
        [EntityReference("businessunits", "_owningbusinessunit_value")]
        public EntityReference OwningBusinessUnit {
            get {
                return this.GetAttributeValue<EntityReference>("owningbusinessunit@odata.bind");
            }
            set {
                this.SetAttributeValue("owningbusinessunit@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the team that owns the record.
        // </summary>
        [EntityReference("teams", "_owningteam_value")]
        public EntityReference OwningTeam {
            get {
                return this.GetAttributeValue<EntityReference>("owningteam@odata.bind");
            }
            set {
                this.SetAttributeValue("owningteam@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the user that owns the record.
        // </summary>
        [EntityReference("systemusers", "_owninguser_value")]
        public EntityReference OwningUser {
            get {
                return this.GetAttributeValue<EntityReference>("owninguser@odata.bind");
            }
            set {
                this.SetAttributeValue("owninguser@odata.bind", value);
            }
        }
        
        // <summary>
        // Status of the Employment
        // </summary>
        public int? statecode {
            get {
                return this.GetAttributeValue<int?>("statecode");
            }
            set {
                this.SetAttributeValue("statecode", value);
            }
        }
        
        // <summary>
        // Reason for the status of the Employment
        // </summary>
        public int? statuscode {
            get {
                return this.GetAttributeValue<int?>("statuscode");
            }
            set {
                this.SetAttributeValue("statuscode", value);
            }
        }
        
        // <summary>
        // For internal use only.
        // </summary>
        public int? TimeZoneRuleVersionNumber {
            get {
                return this.GetAttributeValue<int?>("TimeZoneRuleVersionNumber");
            }
            set {
                this.SetAttributeValue("TimeZoneRuleVersionNumber", value);
            }
        }
        
        // <summary>
        // Time zone code that was in use when the record was created.
        // </summary>
        public int? UTCConversionTimeZoneCode {
            get {
                return this.GetAttributeValue<int?>("UTCConversionTimeZoneCode");
            }
            set {
                this.SetAttributeValue("UTCConversionTimeZoneCode", value);
            }
        }
        
        // <summary>
        // Version Number
        // </summary>
        public long? VersionNumber {
            get {
                return this.GetAttributeValue<long?>("VersionNumber");
            }
            set {
                this.SetAttributeValue("VersionNumber", value);
            }
        }
        
        public class Fields {
            
            public const string _cdm_CompanyId_value = "_cdm_companyid_value";
            
            public const string _cdm_transitionreasoncode_value = "_cdm_transitionreasoncode_value";
            
            public const string _cdm_WorkerId_value = "_cdm_workerid_value";
            
            public const string _CreatedBy_value = "_createdby_value";
            
            public const string _CreatedOnBehalfBy_value = "_createdonbehalfby_value";
            
            public const string _ModifiedBy_value = "_modifiedby_value";
            
            public const string _ModifiedOnBehalfBy_value = "_modifiedonbehalfby_value";
            
            public const string _OwnerId_value = "_ownerid_value";
            
            public const string _OwningBusinessUnit_value = "_owningbusinessunit_value";
            
            public const string _OwningTeam_value = "_owningteam_value";
            
            public const string _OwningUser_value = "_owninguser_value";
            
            public const string cdm_AdjustedWorkerStartDate = "cdm_adjustedworkerstartdate";
            
            public const string cdm_CompanyId = "cdm_companyid";
            
            public const string cdm_CompanyIdName = "cdm_companyidname";
            
            public const string cdm_DimensionDisplayValue = "cdm_dimensiondisplayvalue";
            
            public const string cdm_EmployerNoticeAmount = "cdm_employernoticeamount";
            
            public const string cdm_EmployerUnitofNotice = "cdm_employerunitofnotice";
            
            public const string cdm_employerunitofnoticeName = "cdm_employerunitofnoticename";
            
            public const string cdm_EmploymentEndDate = "cdm_employmentenddate";
            
            public const string cdm_employmentId = "cdm_employmentid";
            
            public const string cdm_EmploymentNumber = "cdm_employmentnumber";
            
            public const string cdm_EmploymentStartDate = "cdm_employmentstartdate";
            
            public const string cdm_LastDateWorked = "cdm_lastdateworked";
            
            public const string cdm_probationenddate = "cdm_probationenddate";
            
            public const string cdm_TransitionDate = "cdm_transitiondate";
            
            public const string cdm_transitionreasoncode = "cdm_transitionreasoncode";
            
            public const string cdm_transitionreasoncodeName = "cdm_transitionreasoncodename";
            
            public const string cdm_ValidFrom = "cdm_validfrom";
            
            public const string cdm_ValidTo = "cdm_validto";
            
            public const string cdm_WorkerId = "cdm_workerid";
            
            public const string cdm_WorkerIdName = "cdm_workeridname";
            
            public const string cdm_WorkerNoticeAmount = "cdm_workernoticeamount";
            
            public const string cdm_WorkerStartDate = "cdm_workerstartdate";
            
            public const string cdm_WorkerType = "cdm_workertype";
            
            public const string cdm_workertypeName = "cdm_workertypename";
            
            public const string cdm_WorkerUnitofNotice = "cdm_workerunitofnotice";
            
            public const string cdm_workerunitofnoticeName = "cdm_workerunitofnoticename";
            
            public const string CreatedBy = "createdby";
            
            public const string CreatedByName = "createdbyname";
            
            public const string CreatedByYomiName = "createdbyyominame";
            
            public const string CreatedOn = "createdon";
            
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            
            public const string CreatedOnBehalfByName = "createdonbehalfbyname";
            
            public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
            
            public const string ImportSequenceNumber = "importsequencenumber";
            
            public const string ModifiedBy = "modifiedby";
            
            public const string ModifiedByName = "modifiedbyname";
            
            public const string ModifiedByYomiName = "modifiedbyyominame";
            
            public const string ModifiedOn = "modifiedon";
            
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            
            public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
            
            public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
            
            public const string OverriddenCreatedOn = "overriddencreatedon";
            
            public const string OwnerId = "ownerid";
            
            public const string OwnerIdName = "owneridname";
            
            public const string OwnerIdType = "owneridtype";
            
            public const string OwnerIdYomiName = "owneridyominame";
            
            public const string OwningBusinessUnit = "owningbusinessunit";
            
            public const string OwningTeam = "owningteam";
            
            public const string OwningUser = "owninguser";
            
            public const string statecode = "statecode";
            
            public const string statecodeName = "statecodename";
            
            public const string statuscode = "statuscode";
            
            public const string statuscodeName = "statuscodename";
            
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
            
            public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
            
            public const string VersionNumber = "versionnumber";
            
            public const string Id = "cdm_employmentid";
        }
        
        public class Properties {
            
            public const string cdm_CompanyId = "cdm_CompanyId";
            
            public const string cdm_transitionreasoncode = "cdm_transitionreasoncode";
            
            public const string cdm_WorkerId = "cdm_WorkerId";
            
            public const string createdby = "createdby";
            
            public const string createdonbehalfby = "createdonbehalfby";
            
            public const string modifiedby = "modifiedby";
            
            public const string modifiedonbehalfby = "modifiedonbehalfby";
            
            public const string ownerid = "ownerid";
            
            public const string owningbusinessunit = "owningbusinessunit";
            
            public const string owningteam = "owningteam";
            
            public const string owninguser = "owninguser";
        }
        
        public class Schemas {
            
            public const string cdm_AdjustedWorkerStartDate = "cdm_AdjustedWorkerStartDate";
            
            public const string cdm_CompanyId = "cdm_CompanyId";
            
            public const string cdm_CompanyIdName = "cdm_CompanyIdName";
            
            public const string cdm_DimensionDisplayValue = "cdm_DimensionDisplayValue";
            
            public const string cdm_EmployerNoticeAmount = "cdm_EmployerNoticeAmount";
            
            public const string cdm_EmployerUnitofNotice = "cdm_EmployerUnitofNotice";
            
            public const string cdm_employerunitofnoticeName = "cdm_employerunitofnoticeName";
            
            public const string cdm_EmploymentEndDate = "cdm_EmploymentEndDate";
            
            public const string cdm_employmentId = "cdm_employmentId";
            
            public const string cdm_EmploymentNumber = "cdm_EmploymentNumber";
            
            public const string cdm_EmploymentStartDate = "cdm_EmploymentStartDate";
            
            public const string cdm_LastDateWorked = "cdm_LastDateWorked";
            
            public const string cdm_probationenddate = "cdm_probationenddate";
            
            public const string cdm_TransitionDate = "cdm_TransitionDate";
            
            public const string cdm_transitionreasoncode = "cdm_transitionreasoncode";
            
            public const string cdm_transitionreasoncodeName = "cdm_transitionreasoncodeName";
            
            public const string cdm_ValidFrom = "cdm_ValidFrom";
            
            public const string cdm_ValidTo = "cdm_ValidTo";
            
            public const string cdm_WorkerId = "cdm_WorkerId";
            
            public const string cdm_WorkerIdName = "cdm_WorkerIdName";
            
            public const string cdm_WorkerNoticeAmount = "cdm_WorkerNoticeAmount";
            
            public const string cdm_WorkerStartDate = "cdm_WorkerStartDate";
            
            public const string cdm_WorkerType = "cdm_WorkerType";
            
            public const string cdm_workertypeName = "cdm_workertypeName";
            
            public const string cdm_WorkerUnitofNotice = "cdm_WorkerUnitofNotice";
            
            public const string cdm_workerunitofnoticeName = "cdm_workerunitofnoticeName";
            
            public const string CreatedBy = "CreatedBy";
            
            public const string CreatedByName = "CreatedByName";
            
            public const string CreatedByYomiName = "CreatedByYomiName";
            
            public const string CreatedOn = "CreatedOn";
            
            public const string CreatedOnBehalfBy = "CreatedOnBehalfBy";
            
            public const string CreatedOnBehalfByName = "CreatedOnBehalfByName";
            
            public const string CreatedOnBehalfByYomiName = "CreatedOnBehalfByYomiName";
            
            public const string ImportSequenceNumber = "ImportSequenceNumber";
            
            public const string ModifiedBy = "ModifiedBy";
            
            public const string ModifiedByName = "ModifiedByName";
            
            public const string ModifiedByYomiName = "ModifiedByYomiName";
            
            public const string ModifiedOn = "ModifiedOn";
            
            public const string ModifiedOnBehalfBy = "ModifiedOnBehalfBy";
            
            public const string ModifiedOnBehalfByName = "ModifiedOnBehalfByName";
            
            public const string ModifiedOnBehalfByYomiName = "ModifiedOnBehalfByYomiName";
            
            public const string OverriddenCreatedOn = "OverriddenCreatedOn";
            
            public const string OwnerId = "OwnerId";
            
            public const string OwnerIdName = "OwnerIdName";
            
            public const string OwnerIdType = "OwnerIdType";
            
            public const string OwnerIdYomiName = "OwnerIdYomiName";
            
            public const string OwningBusinessUnit = "OwningBusinessUnit";
            
            public const string OwningTeam = "OwningTeam";
            
            public const string OwningUser = "OwningUser";
            
            public const string statecode = "statecode";
            
            public const string statecodeName = "statecodeName";
            
            public const string statuscode = "statuscode";
            
            public const string statuscodeName = "statuscodeName";
            
            public const string TimeZoneRuleVersionNumber = "TimeZoneRuleVersionNumber";
            
            public const string UTCConversionTimeZoneCode = "UTCConversionTimeZoneCode";
            
            public const string VersionNumber = "VersionNumber";
        }
    }
}
