//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    using System.Reflection;
    using System.Linq;
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.Diagnostics.CodeAnalysis;
    
    
    [ExcludeFromCodeCoverageAttribute()]
    public class cdm_worker : Entity {
        
        public new const string EntityLogicalName = "cdm_worker";
        
        public new const string EntitySetName = "cdm_workers";
        
        public new const string PrimaryIdAttribute = "cdm_workerid";
        
        public cdm_worker() {
        }
        
        public cdm_worker(ExpandoObject expandoObject) : 
                base(expandoObject) {
        }
        
        // <summary>
        // The anniversary date for the worker
        // </summary>
        public DateTime? cdm_anniversarydatetime {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_anniversarydatetime");
            }
            set {
                this.SetAttributeValue("cdm_anniversarydatetime", value);
            }
        }
        
        // <summary>
        // The birthdate of the worker
        // </summary>
        [OnlyDate()]
        public DateTime? cdm_Birthdate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_Birthdate");
            }
            set {
                this.SetAttributeValue("cdm_Birthdate", value);
            }
        }
        
        // <summary>
        // The description of the worker
        // </summary>
        public String cdm_Description {
            get {
                return this.GetAttributeValue<String>("cdm_Description");
            }
            set {
                this.SetAttributeValue("cdm_Description", value);
            }
        }
        
        // <summary>
        // The first alternate email address of the worker
        // </summary>
        public String cdm_EmailAddress1 {
            get {
                return this.GetAttributeValue<String>("cdm_EmailAddress1");
            }
            set {
                this.SetAttributeValue("cdm_EmailAddress1", value);
            }
        }
        
        // <summary>
        // The second alternate email address of the worker
        // </summary>
        public String cdm_EmailAddress2 {
            get {
                return this.GetAttributeValue<String>("cdm_EmailAddress2");
            }
            set {
                this.SetAttributeValue("cdm_EmailAddress2", value);
            }
        }
        
        // <summary>
        // The Facebook identity of the worker
        // </summary>
        public String cdm_FacebookIdentity {
            get {
                return this.GetAttributeValue<String>("cdm_FacebookIdentity");
            }
            set {
                this.SetAttributeValue("cdm_FacebookIdentity", value);
            }
        }
        
        // <summary>
        // The given name of the worker
        // </summary>
        public String cdm_FirstName {
            get {
                return this.GetAttributeValue<String>("cdm_FirstName");
            }
            set {
                this.SetAttributeValue("cdm_FirstName", value);
            }
        }
        
        // <summary>
        // The combination of the first, middle, and last name of the worker
        // </summary>
        public String cdm_FullName {
            get {
                return this.GetAttributeValue<String>("cdm_FullName");
            }
            set {
                this.SetAttributeValue("cdm_FullName", value);
            }
        }
        
        // <summary>
        // The gender of the worker
        // </summary>
        public int? cdm_Gender {
            get {
                return this.GetAttributeValue<int?>("cdm_Gender");
            }
            set {
                this.SetAttributeValue("cdm_Gender", value);
            }
        }
        
        // <summary>
        // The generation of the worker
        // </summary>
        public String cdm_Generation {
            get {
                return this.GetAttributeValue<String>("cdm_Generation");
            }
            set {
                this.SetAttributeValue("cdm_Generation", value);
            }
        }
        
        // <summary>
        // Determines whether contact of this worker via email is permitted
        // </summary>
        public bool? cdm_IsEmailContactAllowed {
            get {
                return this.GetAttributeValue<bool?>("cdm_IsEmailContactAllowed");
            }
            set {
                this.SetAttributeValue("cdm_IsEmailContactAllowed", value);
            }
        }
        
        // <summary>
        // Determines whether contact of the worker via phone is permitted
        // </summary>
        public bool? cdm_IsPhoneContactAllowed {
            get {
                return this.GetAttributeValue<bool?>("cdm_IsPhoneContactAllowed");
            }
            set {
                this.SetAttributeValue("cdm_IsPhoneContactAllowed", value);
            }
        }
        
        // <summary>
        // The known as name for the worker
        // </summary>
        public String cdm_knownas {
            get {
                return this.GetAttributeValue<String>("cdm_knownas");
            }
            set {
                this.SetAttributeValue("cdm_knownas", value);
            }
        }
        
        // <summary>
        // The worker's primary language
        // </summary>
        public String cdm_LanguageId {
            get {
                return this.GetAttributeValue<String>("cdm_LanguageId");
            }
            set {
                this.SetAttributeValue("cdm_LanguageId", value);
            }
        }
        
        // <summary>
        // The last name of the worker.
        // </summary>
        public String cdm_LastName {
            get {
                return this.GetAttributeValue<String>("cdm_LastName");
            }
            set {
                this.SetAttributeValue("cdm_LastName", value);
            }
        }
        
        // <summary>
        // The LinkedIn identity of the worker
        // </summary>
        public String cdm_LinkedInIdentity {
            get {
                return this.GetAttributeValue<String>("cdm_LinkedInIdentity");
            }
            set {
                this.SetAttributeValue("cdm_LinkedInIdentity", value);
            }
        }
        
        // <summary>
        // The manager of the worker
        // </summary>
        [EntityReference("cdm_workers", "_cdm_managerworkerid_value")]
        public EntityReference cdm_ManagerWorkerId {
            get {
                return this.GetAttributeValue<EntityReference>("cdm_ManagerWorkerId@odata.bind");
            }
            set {
                this.SetAttributeValue("cdm_ManagerWorkerId@odata.bind", value);
            }
        }
        
        // <summary>
        // The manager of the worker
        // </summary>
        [Entity("cdm_worker", "cdm_ManagerWorkerId")]
        public cdm_worker cdm_ManagerWorkerIdEntity {
            get {
                return this.GetAttributeValue<cdm_worker>("cdm_ManagerWorkerId");
            }
            set {
                this.SetAttributeValue("cdm_ManagerWorkerId", value);
            }
        }
        
        // <summary>
        // The middle name of the worker
        // </summary>
        public String cdm_MiddleName {
            get {
                return this.GetAttributeValue<String>("cdm_MiddleName");
            }
            set {
                this.SetAttributeValue("cdm_MiddleName", value);
            }
        }
        
        // <summary>
        // The mobile phone number of the worker
        // </summary>
        public String cdm_MobilePhone {
            get {
                return this.GetAttributeValue<String>("cdm_MobilePhone");
            }
            set {
                this.SetAttributeValue("cdm_MobilePhone", value);
            }
        }
        
        // <summary>
        // The name sequence format for the worker
        // </summary>
        public String cdm_namesequencedisplayas {
            get {
                return this.GetAttributeValue<String>("cdm_namesequencedisplayas");
            }
            set {
                this.SetAttributeValue("cdm_namesequencedisplayas", value);
            }
        }
        
        // <summary>
        // The Office Graph identifier of the worker
        // </summary>
        public String cdm_OfficeGraphIdentifier {
            get {
                return this.GetAttributeValue<String>("cdm_OfficeGraphIdentifier");
            }
            set {
                this.SetAttributeValue("cdm_OfficeGraphIdentifier", value);
            }
        }
        
        // <summary>
        // The original hire date for the worker
        // </summary>
        public DateTime? cdm_originalhiredatetime {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_originalhiredatetime");
            }
            set {
                this.SetAttributeValue("cdm_originalhiredatetime", value);
            }
        }
        
        // <summary>
        // The primary email address of the worker
        // </summary>
        public String cdm_PrimaryEmailAddress {
            get {
                return this.GetAttributeValue<String>("cdm_PrimaryEmailAddress");
            }
            set {
                this.SetAttributeValue("cdm_PrimaryEmailAddress", value);
            }
        }
        
        // <summary>
        // The primary telephone number of the worker.
        // </summary>
        public String cdm_PrimaryTelephone {
            get {
                return this.GetAttributeValue<String>("cdm_PrimaryTelephone");
            }
            set {
                this.SetAttributeValue("cdm_PrimaryTelephone", value);
            }
        }
        
        // <summary>
        // The profession of the worker
        // </summary>
        public String cdm_Profession {
            get {
                return this.GetAttributeValue<String>("cdm_Profession");
            }
            set {
                this.SetAttributeValue("cdm_Profession", value);
            }
        }
        
        // <summary>
        // The seniority date for the worker
        // </summary>
        public DateTime? cdm_senioritydate {
            get {
                return this.GetAttributeValue<DateTime?>("cdm_senioritydate");
            }
            set {
                this.SetAttributeValue("cdm_senioritydate", value);
            }
        }
        
        // <summary>
        // The first alternate social network
        // </summary>
        public int? cdm_SocialNetwork01 {
            get {
                return this.GetAttributeValue<int?>("cdm_SocialNetwork01");
            }
            set {
                this.SetAttributeValue("cdm_SocialNetwork01", value);
            }
        }
        
        // <summary>
        // The second alterative social network
        // </summary>
        public int? cdm_SocialNetwork02 {
            get {
                return this.GetAttributeValue<int?>("cdm_SocialNetwork02");
            }
            set {
                this.SetAttributeValue("cdm_SocialNetwork02", value);
            }
        }
        
        // <summary>
        // The identity related to social network 1
        // </summary>
        public String cdm_SocialNetworkIdentity01 {
            get {
                return this.GetAttributeValue<String>("cdm_SocialNetworkIdentity01");
            }
            set {
                this.SetAttributeValue("cdm_SocialNetworkIdentity01", value);
            }
        }
        
        // <summary>
        // The identity related to social network 2
        // </summary>
        public String cdm_SocialNetworkIdentity02 {
            get {
                return this.GetAttributeValue<String>("cdm_SocialNetworkIdentity02");
            }
            set {
                this.SetAttributeValue("cdm_SocialNetworkIdentity02", value);
            }
        }
        
        // <summary>
        // The source of the worker
        // </summary>
        public int? cdm_Source {
            get {
                return this.GetAttributeValue<int?>("cdm_Source");
            }
            set {
                this.SetAttributeValue("cdm_Source", value);
            }
        }
        
        // <summary>
        // The status of the worker  Example: Active, Inactive
        // </summary>
        public int? cdm_Status {
            get {
                return this.GetAttributeValue<int?>("cdm_Status");
            }
            set {
                this.SetAttributeValue("cdm_Status", value);
            }
        }
        
        // <summary>
        // The first alternate telephone number of the worker.
        // </summary>
        public String cdm_Telephone1 {
            get {
                return this.GetAttributeValue<String>("cdm_Telephone1");
            }
            set {
                this.SetAttributeValue("cdm_Telephone1", value);
            }
        }
        
        // <summary>
        // The second alternate telephone number of the worker.
        // </summary>
        public String cdm_Telephone2 {
            get {
                return this.GetAttributeValue<String>("cdm_Telephone2");
            }
            set {
                this.SetAttributeValue("cdm_Telephone2", value);
            }
        }
        
        // <summary>
        // The third alternate phone number of the worker.
        // </summary>
        public String cdm_Telephone3 {
            get {
                return this.GetAttributeValue<String>("cdm_Telephone3");
            }
            set {
                this.SetAttributeValue("cdm_Telephone3", value);
            }
        }
        
        // <summary>
        // The Twitter identity of the worker.
        // </summary>
        public String cdm_TwitterIdentity {
            get {
                return this.GetAttributeValue<String>("cdm_TwitterIdentity");
            }
            set {
                this.SetAttributeValue("cdm_TwitterIdentity", value);
            }
        }
        
        // <summary>
        // The type of the worker.
        // </summary>
        public int? cdm_Type {
            get {
                return this.GetAttributeValue<int?>("cdm_Type");
            }
            set {
                this.SetAttributeValue("cdm_Type", value);
            }
        }
        
        // <summary>
        // The URL of the worker's personal website.
        // </summary>
        public String cdm_WebsiteURL {
            get {
                return this.GetAttributeValue<String>("cdm_WebsiteURL");
            }
            set {
                this.SetAttributeValue("cdm_WebsiteURL", value);
            }
        }
        
        // <summary>
        // Unique identifier for entity instances
        // </summary>
        public Guid? cdm_workerId {
            get {
                return this.GetAttributeValue<Guid?>("cdm_workerId");
            }
            set {
                this.SetAttributeValue("cdm_workerId", value);
            }
        }
        
        // <summary>
        // The number of the worker
        // </summary>
        public String cdm_WorkerNumber {
            get {
                return this.GetAttributeValue<String>("cdm_WorkerNumber");
            }
            set {
                this.SetAttributeValue("cdm_WorkerNumber", value);
            }
        }
        
        // <summary>
        // Indicates if the worker works from home
        // </summary>
        public bool? cdm_WorksFromHome {
            get {
                return this.GetAttributeValue<bool?>("cdm_WorksFromHome");
            }
            set {
                this.SetAttributeValue("cdm_WorksFromHome", value);
            }
        }
        
        // <summary>
        // The phonetic annunciation of the first name of the worker
        // </summary>
        public String cdm_YomiFirstName {
            get {
                return this.GetAttributeValue<String>("cdm_YomiFirstName");
            }
            set {
                this.SetAttributeValue("cdm_YomiFirstName", value);
            }
        }
        
        // <summary>
        // The phonetic annunciation of the full name of the worker
        // </summary>
        public String cdm_YomiFullName {
            get {
                return this.GetAttributeValue<String>("cdm_YomiFullName");
            }
            set {
                this.SetAttributeValue("cdm_YomiFullName", value);
            }
        }
        
        // <summary>
        // The phonetic annunciation of the last name of the worker
        // </summary>
        public String cdm_YomiLastName {
            get {
                return this.GetAttributeValue<String>("cdm_YomiLastName");
            }
            set {
                this.SetAttributeValue("cdm_YomiLastName", value);
            }
        }
        
        // <summary>
        // The phonetic annunciation of the middle name of the worker
        // </summary>
        public String cdm_YomiMiddleName {
            get {
                return this.GetAttributeValue<String>("cdm_YomiMiddleName");
            }
            set {
                this.SetAttributeValue("cdm_YomiMiddleName", value);
            }
        }
        
        // <summary>
        // Unique identifier of the user who created the record.
        // </summary>
        [EntityReference("systemusers", "_createdby_value")]
        public EntityReference CreatedBy {
            get {
                return this.GetAttributeValue<EntityReference>("createdby@odata.bind");
            }
            set {
                this.SetAttributeValue("createdby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time when the record was created.
        // </summary>
        public DateTime? CreatedOn {
            get {
                return this.GetAttributeValue<DateTime?>("CreatedOn");
            }
            set {
                this.SetAttributeValue("CreatedOn", value);
            }
        }
        
        // <summary>
        // Unique identifier of the delegate user who created the record.
        // </summary>
        [EntityReference("systemusers", "_createdonbehalfby_value")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return this.GetAttributeValue<EntityReference>("createdonbehalfby@odata.bind");
            }
            set {
                this.SetAttributeValue("createdonbehalfby@odata.bind", value);
            }
        }
        
        // <summary>
        // Sequence number of the import that created this record.
        // </summary>
        public int? ImportSequenceNumber {
            get {
                return this.GetAttributeValue<int?>("ImportSequenceNumber");
            }
            set {
                this.SetAttributeValue("ImportSequenceNumber", value);
            }
        }
        
        // <summary>
        // Unique identifier of the user who modified the record.
        // </summary>
        [EntityReference("systemusers", "_modifiedby_value")]
        public EntityReference ModifiedBy {
            get {
                return this.GetAttributeValue<EntityReference>("modifiedby@odata.bind");
            }
            set {
                this.SetAttributeValue("modifiedby@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time when the record was modified.
        // </summary>
        public DateTime? ModifiedOn {
            get {
                return this.GetAttributeValue<DateTime?>("ModifiedOn");
            }
            set {
                this.SetAttributeValue("ModifiedOn", value);
            }
        }
        
        // <summary>
        // Unique identifier of the delegate user who modified the record.
        // </summary>
        [EntityReference("systemusers", "_modifiedonbehalfby_value")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return this.GetAttributeValue<EntityReference>("modifiedonbehalfby@odata.bind");
            }
            set {
                this.SetAttributeValue("modifiedonbehalfby@odata.bind", value);
            }
        }
        
        // <summary>
        // Reference to LinkedIn member identifier
        // </summary>
        public String msdyn_LinkedInmemberreference {
            get {
                return this.GetAttributeValue<String>("msdyn_LinkedInmemberreference");
            }
            set {
                this.SetAttributeValue("msdyn_LinkedInmemberreference", value);
            }
        }
        
        // <summary>
        // Unique identifier for User associated with Worker.
        // </summary>
        [EntityReference("systemusers", "_msdyn_userid_value")]
        public EntityReference msdyn_UserId {
            get {
                return this.GetAttributeValue<EntityReference>("msdyn_UserId@odata.bind");
            }
            set {
                this.SetAttributeValue("msdyn_UserId@odata.bind", value);
            }
        }
        
        // <summary>
        // Date and time that the record was migrated.
        // </summary>
        [OnlyDate()]
        public DateTime? OverriddenCreatedOn {
            get {
                return this.GetAttributeValue<DateTime?>("OverriddenCreatedOn");
            }
            set {
                this.SetAttributeValue("OverriddenCreatedOn", value);
            }
        }
        
        // <summary>
        // Owner Id
        // </summary>
        [EntityReference("systemusers", "_ownerid_value")]
        public EntityReference OwnerId {
            get {
                return this.GetAttributeValue<EntityReference>("OwnerId@odata.bind");
            }
            set {
                this.SetAttributeValue("OwnerId@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the business unit that owns the record
        // </summary>
        [EntityReference("businessunits", "_owningbusinessunit_value")]
        public EntityReference OwningBusinessUnit {
            get {
                return this.GetAttributeValue<EntityReference>("owningbusinessunit@odata.bind");
            }
            set {
                this.SetAttributeValue("owningbusinessunit@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the team that owns the record.
        // </summary>
        [EntityReference("teams", "_owningteam_value")]
        public EntityReference OwningTeam {
            get {
                return this.GetAttributeValue<EntityReference>("owningteam@odata.bind");
            }
            set {
                this.SetAttributeValue("owningteam@odata.bind", value);
            }
        }
        
        // <summary>
        // Unique identifier for the user that owns the record.
        // </summary>
        [EntityReference("systemusers", "_owninguser_value")]
        public EntityReference OwningUser {
            get {
                return this.GetAttributeValue<EntityReference>("owninguser@odata.bind");
            }
            set {
                this.SetAttributeValue("owninguser@odata.bind", value);
            }
        }
        
        // <summary>
        // Status of the Worker
        // </summary>
        public int? statecode {
            get {
                return this.GetAttributeValue<int?>("statecode");
            }
            set {
                this.SetAttributeValue("statecode", value);
            }
        }
        
        // <summary>
        // Reason for the status of the Worker
        // </summary>
        public int? statuscode {
            get {
                return this.GetAttributeValue<int?>("statuscode");
            }
            set {
                this.SetAttributeValue("statuscode", value);
            }
        }
        
        // <summary>
        // For internal use only.
        // </summary>
        public int? TimeZoneRuleVersionNumber {
            get {
                return this.GetAttributeValue<int?>("TimeZoneRuleVersionNumber");
            }
            set {
                this.SetAttributeValue("TimeZoneRuleVersionNumber", value);
            }
        }
        
        // <summary>
        // Time zone code that was in use when the record was created.
        // </summary>
        public int? UTCConversionTimeZoneCode {
            get {
                return this.GetAttributeValue<int?>("UTCConversionTimeZoneCode");
            }
            set {
                this.SetAttributeValue("UTCConversionTimeZoneCode", value);
            }
        }
        
        // <summary>
        // Version Number
        // </summary>
        public long? VersionNumber {
            get {
                return this.GetAttributeValue<long?>("VersionNumber");
            }
            set {
                this.SetAttributeValue("VersionNumber", value);
            }
        }
        
        public class Fields {
            
            public const string _cdm_ManagerWorkerId_value = "_cdm_managerworkerid_value";
            
            public const string _CreatedBy_value = "_createdby_value";
            
            public const string _CreatedOnBehalfBy_value = "_createdonbehalfby_value";
            
            public const string _ModifiedBy_value = "_modifiedby_value";
            
            public const string _ModifiedOnBehalfBy_value = "_modifiedonbehalfby_value";
            
            public const string _msdyn_UserId_value = "_msdyn_userid_value";
            
            public const string _OwnerId_value = "_ownerid_value";
            
            public const string _OwningBusinessUnit_value = "_owningbusinessunit_value";
            
            public const string _OwningTeam_value = "_owningteam_value";
            
            public const string _OwningUser_value = "_owninguser_value";
            
            public const string cdm_anniversarydatetime = "cdm_anniversarydatetime";
            
            public const string cdm_Birthdate = "cdm_birthdate";
            
            public const string cdm_Description = "cdm_description";
            
            public const string cdm_EmailAddress1 = "cdm_emailaddress1";
            
            public const string cdm_EmailAddress2 = "cdm_emailaddress2";
            
            public const string cdm_FacebookIdentity = "cdm_facebookidentity";
            
            public const string cdm_FirstName = "cdm_firstname";
            
            public const string cdm_FullName = "cdm_fullname";
            
            public const string cdm_Gender = "cdm_gender";
            
            public const string cdm_genderName = "cdm_gendername";
            
            public const string cdm_Generation = "cdm_generation";
            
            public const string cdm_IsEmailContactAllowed = "cdm_isemailcontactallowed";
            
            public const string cdm_isemailcontactallowedName = "cdm_isemailcontactallowedname";
            
            public const string cdm_IsPhoneContactAllowed = "cdm_isphonecontactallowed";
            
            public const string cdm_isphonecontactallowedName = "cdm_isphonecontactallowedname";
            
            public const string cdm_knownas = "cdm_knownas";
            
            public const string cdm_LanguageId = "cdm_languageid";
            
            public const string cdm_LastName = "cdm_lastname";
            
            public const string cdm_LinkedInIdentity = "cdm_linkedinidentity";
            
            public const string cdm_ManagerWorkerId = "cdm_managerworkerid";
            
            public const string cdm_ManagerWorkerIdName = "cdm_managerworkeridname";
            
            public const string cdm_MiddleName = "cdm_middlename";
            
            public const string cdm_MobilePhone = "cdm_mobilephone";
            
            public const string cdm_namesequencedisplayas = "cdm_namesequencedisplayas";
            
            public const string cdm_OfficeGraphIdentifier = "cdm_officegraphidentifier";
            
            public const string cdm_originalhiredatetime = "cdm_originalhiredatetime";
            
            public const string cdm_PrimaryEmailAddress = "cdm_primaryemailaddress";
            
            public const string cdm_PrimaryTelephone = "cdm_primarytelephone";
            
            public const string cdm_Profession = "cdm_profession";
            
            public const string cdm_senioritydate = "cdm_senioritydate";
            
            public const string cdm_SocialNetwork01 = "cdm_socialnetwork01";
            
            public const string cdm_socialnetwork01Name = "cdm_socialnetwork01name";
            
            public const string cdm_SocialNetwork02 = "cdm_socialnetwork02";
            
            public const string cdm_socialnetwork02Name = "cdm_socialnetwork02name";
            
            public const string cdm_SocialNetworkIdentity01 = "cdm_socialnetworkidentity01";
            
            public const string cdm_SocialNetworkIdentity02 = "cdm_socialnetworkidentity02";
            
            public const string cdm_Source = "cdm_source";
            
            public const string cdm_sourceName = "cdm_sourcename";
            
            public const string cdm_Status = "cdm_status";
            
            public const string cdm_statusName = "cdm_statusname";
            
            public const string cdm_Telephone1 = "cdm_telephone1";
            
            public const string cdm_Telephone2 = "cdm_telephone2";
            
            public const string cdm_Telephone3 = "cdm_telephone3";
            
            public const string cdm_TwitterIdentity = "cdm_twitteridentity";
            
            public const string cdm_Type = "cdm_type";
            
            public const string cdm_typeName = "cdm_typename";
            
            public const string cdm_WebsiteURL = "cdm_websiteurl";
            
            public const string cdm_workerId = "cdm_workerid";
            
            public const string cdm_WorkerNumber = "cdm_workernumber";
            
            public const string cdm_WorksFromHome = "cdm_worksfromhome";
            
            public const string cdm_worksfromhomeName = "cdm_worksfromhomename";
            
            public const string cdm_YomiFirstName = "cdm_yomifirstname";
            
            public const string cdm_YomiFullName = "cdm_yomifullname";
            
            public const string cdm_YomiLastName = "cdm_yomilastname";
            
            public const string cdm_YomiMiddleName = "cdm_yomimiddlename";
            
            public const string CreatedBy = "createdby";
            
            public const string CreatedByName = "createdbyname";
            
            public const string CreatedByYomiName = "createdbyyominame";
            
            public const string CreatedOn = "createdon";
            
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            
            public const string CreatedOnBehalfByName = "createdonbehalfbyname";
            
            public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
            
            public const string ImportSequenceNumber = "importsequencenumber";
            
            public const string ModifiedBy = "modifiedby";
            
            public const string ModifiedByName = "modifiedbyname";
            
            public const string ModifiedByYomiName = "modifiedbyyominame";
            
            public const string ModifiedOn = "modifiedon";
            
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            
            public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
            
            public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
            
            public const string msdyn_LinkedInmemberreference = "msdyn_linkedinmemberreference";
            
            public const string msdyn_UserId = "msdyn_userid";
            
            public const string msdyn_UserIdName = "msdyn_useridname";
            
            public const string msdyn_UserIdYomiName = "msdyn_useridyominame";
            
            public const string OverriddenCreatedOn = "overriddencreatedon";
            
            public const string OwnerId = "ownerid";
            
            public const string OwnerIdName = "owneridname";
            
            public const string OwnerIdType = "owneridtype";
            
            public const string OwnerIdYomiName = "owneridyominame";
            
            public const string OwningBusinessUnit = "owningbusinessunit";
            
            public const string OwningTeam = "owningteam";
            
            public const string OwningUser = "owninguser";
            
            public const string statecode = "statecode";
            
            public const string statecodeName = "statecodename";
            
            public const string statuscode = "statuscode";
            
            public const string statuscodeName = "statuscodename";
            
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
            
            public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
            
            public const string VersionNumber = "versionnumber";
            
            public const string Id = "cdm_workerid";
        }
        
        public class Properties {
            
            public const string cdm_ManagerWorkerId = "cdm_ManagerWorkerId";
            
            public const string createdby = "createdby";
            
            public const string createdonbehalfby = "createdonbehalfby";
            
            public const string modifiedby = "modifiedby";
            
            public const string modifiedonbehalfby = "modifiedonbehalfby";
            
            public const string msdyn_jobopeningparticipant_cdm_worker = "msdyn_jobopeningparticipant_cdm_worker";
            
            public const string msdyn_UserId = "msdyn_UserId";
            
            public const string ownerid = "ownerid";
            
            public const string owningbusinessunit = "owningbusinessunit";
            
            public const string owningteam = "owningteam";
            
            public const string owninguser = "owninguser";
        }
        
        public class Schemas {
            
            public const string cdm_anniversarydatetime = "cdm_anniversarydatetime";
            
            public const string cdm_Birthdate = "cdm_Birthdate";
            
            public const string cdm_Description = "cdm_Description";
            
            public const string cdm_EmailAddress1 = "cdm_EmailAddress1";
            
            public const string cdm_EmailAddress2 = "cdm_EmailAddress2";
            
            public const string cdm_FacebookIdentity = "cdm_FacebookIdentity";
            
            public const string cdm_FirstName = "cdm_FirstName";
            
            public const string cdm_FullName = "cdm_FullName";
            
            public const string cdm_Gender = "cdm_Gender";
            
            public const string cdm_genderName = "cdm_genderName";
            
            public const string cdm_Generation = "cdm_Generation";
            
            public const string cdm_IsEmailContactAllowed = "cdm_IsEmailContactAllowed";
            
            public const string cdm_isemailcontactallowedName = "cdm_isemailcontactallowedName";
            
            public const string cdm_IsPhoneContactAllowed = "cdm_IsPhoneContactAllowed";
            
            public const string cdm_isphonecontactallowedName = "cdm_isphonecontactallowedName";
            
            public const string cdm_knownas = "cdm_knownas";
            
            public const string cdm_LanguageId = "cdm_LanguageId";
            
            public const string cdm_LastName = "cdm_LastName";
            
            public const string cdm_LinkedInIdentity = "cdm_LinkedInIdentity";
            
            public const string cdm_ManagerWorkerId = "cdm_ManagerWorkerId";
            
            public const string cdm_ManagerWorkerIdName = "cdm_ManagerWorkerIdName";
            
            public const string cdm_MiddleName = "cdm_MiddleName";
            
            public const string cdm_MobilePhone = "cdm_MobilePhone";
            
            public const string cdm_namesequencedisplayas = "cdm_namesequencedisplayas";
            
            public const string cdm_OfficeGraphIdentifier = "cdm_OfficeGraphIdentifier";
            
            public const string cdm_originalhiredatetime = "cdm_originalhiredatetime";
            
            public const string cdm_PrimaryEmailAddress = "cdm_PrimaryEmailAddress";
            
            public const string cdm_PrimaryTelephone = "cdm_PrimaryTelephone";
            
            public const string cdm_Profession = "cdm_Profession";
            
            public const string cdm_senioritydate = "cdm_senioritydate";
            
            public const string cdm_SocialNetwork01 = "cdm_SocialNetwork01";
            
            public const string cdm_socialnetwork01Name = "cdm_socialnetwork01Name";
            
            public const string cdm_SocialNetwork02 = "cdm_SocialNetwork02";
            
            public const string cdm_socialnetwork02Name = "cdm_socialnetwork02Name";
            
            public const string cdm_SocialNetworkIdentity01 = "cdm_SocialNetworkIdentity01";
            
            public const string cdm_SocialNetworkIdentity02 = "cdm_SocialNetworkIdentity02";
            
            public const string cdm_Source = "cdm_Source";
            
            public const string cdm_sourceName = "cdm_sourceName";
            
            public const string cdm_Status = "cdm_Status";
            
            public const string cdm_statusName = "cdm_statusName";
            
            public const string cdm_Telephone1 = "cdm_Telephone1";
            
            public const string cdm_Telephone2 = "cdm_Telephone2";
            
            public const string cdm_Telephone3 = "cdm_Telephone3";
            
            public const string cdm_TwitterIdentity = "cdm_TwitterIdentity";
            
            public const string cdm_Type = "cdm_Type";
            
            public const string cdm_typeName = "cdm_typeName";
            
            public const string cdm_WebsiteURL = "cdm_WebsiteURL";
            
            public const string cdm_workerId = "cdm_workerId";
            
            public const string cdm_WorkerNumber = "cdm_WorkerNumber";
            
            public const string cdm_WorksFromHome = "cdm_WorksFromHome";
            
            public const string cdm_worksfromhomeName = "cdm_worksfromhomeName";
            
            public const string cdm_YomiFirstName = "cdm_YomiFirstName";
            
            public const string cdm_YomiFullName = "cdm_YomiFullName";
            
            public const string cdm_YomiLastName = "cdm_YomiLastName";
            
            public const string cdm_YomiMiddleName = "cdm_YomiMiddleName";
            
            public const string CreatedBy = "CreatedBy";
            
            public const string CreatedByName = "CreatedByName";
            
            public const string CreatedByYomiName = "CreatedByYomiName";
            
            public const string CreatedOn = "CreatedOn";
            
            public const string CreatedOnBehalfBy = "CreatedOnBehalfBy";
            
            public const string CreatedOnBehalfByName = "CreatedOnBehalfByName";
            
            public const string CreatedOnBehalfByYomiName = "CreatedOnBehalfByYomiName";
            
            public const string ImportSequenceNumber = "ImportSequenceNumber";
            
            public const string ModifiedBy = "ModifiedBy";
            
            public const string ModifiedByName = "ModifiedByName";
            
            public const string ModifiedByYomiName = "ModifiedByYomiName";
            
            public const string ModifiedOn = "ModifiedOn";
            
            public const string ModifiedOnBehalfBy = "ModifiedOnBehalfBy";
            
            public const string ModifiedOnBehalfByName = "ModifiedOnBehalfByName";
            
            public const string ModifiedOnBehalfByYomiName = "ModifiedOnBehalfByYomiName";
            
            public const string msdyn_LinkedInmemberreference = "msdyn_LinkedInmemberreference";
            
            public const string msdyn_UserId = "msdyn_UserId";
            
            public const string msdyn_UserIdName = "msdyn_UserIdName";
            
            public const string msdyn_UserIdYomiName = "msdyn_UserIdYomiName";
            
            public const string OverriddenCreatedOn = "OverriddenCreatedOn";
            
            public const string OwnerId = "OwnerId";
            
            public const string OwnerIdName = "OwnerIdName";
            
            public const string OwnerIdType = "OwnerIdType";
            
            public const string OwnerIdYomiName = "OwnerIdYomiName";
            
            public const string OwningBusinessUnit = "OwningBusinessUnit";
            
            public const string OwningTeam = "OwningTeam";
            
            public const string OwningUser = "OwningUser";
            
            public const string statecode = "statecode";
            
            public const string statecodeName = "statecodeName";
            
            public const string statuscode = "statuscode";
            
            public const string statuscodeName = "statuscodeName";
            
            public const string TimeZoneRuleVersionNumber = "TimeZoneRuleVersionNumber";
            
            public const string UTCConversionTimeZoneCode = "UTCConversionTimeZoneCode";
            
            public const string VersionNumber = "VersionNumber";
        }
    }
}
