//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    public enum bet_Status {
        
        Draft = 278270000,
        
        Rejected = 278270001,
        
        Approved = 278270002,
        
        In_review = 278270003,
    }
}
