//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    public enum bet_Earningtype {
        
        Regular_hours = 278270000,
        
        Overtime_hours = 278270001,
        
        Business_travel = 278270002,
        
        Absence = 278270003,
        
        Holiday = 278270004,
        
        Travel = 278270005,
        
        Meal = 278270006,
        
        Addition = 278270007,
    }
}
