//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // The type of employment held by the worker  Example:   Employee, Contractor, Volunteer
    // </summary>
    public enum cdm_WorkerType {
        
        // <summary>
        // Employee
        // </summary>
        Employee = 754400000,
        
        // <summary>
        // Contractor
        // </summary>
        Contractor = 754400001,
        
        // <summary>
        // Volunteer
        // </summary>
        Volunteer = 754400002,
        
        // <summary>
        // Unspecified
        // </summary>
        Unspecified = 754400003,
    }
}
