//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // The source of the worker
    // </summary>
    public enum cdm_Source {
        
        // <summary>
        // Default
        // </summary>
        Default = 754400000,
        
        // <summary>
        // Dynamics 365 for Operations and Finance
        // </summary>
        Operations = 754400001,
        
        // <summary>
        // Dynamics 365 for Customer Engagement
        // </summary>
        Customer_Engagement = 754400002,
        
        // <summary>
        // Dynamics 365 for Finance
        // </summary>
        Finance = 754400003,
        
        // <summary>
        // Dynamics 365 Talent - Attract
        // </summary>
        Attract = 754400004,
        
        // <summary>
        // Dynamics 365 Talent - Onboarding
        // </summary>
        Onboarding = 754400005,
        
        // <summary>
        // Dynamics 365 Talent - Gauge
        // </summary>
        Gauge = 754400006,
        
        // <summary>
        // LinkedIn
        // </summary>
        LinkedIn = 754400007,
        
        // <summary>
        // Greenhouse
        // </summary>
        Greenhouse = 754400008,
        
        // <summary>
        // iCIMS
        // </summary>
        iCIMS = 754400009,
        
        // <summary>
        // Dynamics 365 Human Resources
        // </summary>
        Human_Resources = 754400010,
    }
}
