//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // The second alterative social network
    // </summary>
    public enum cdm_SocialNetwork02 {
        
        // <summary>
        // Facebook
        // </summary>
        Facebook = 754400000,
        
        // <summary>
        // Twitter
        // </summary>
        Twitter = 754400001,
        
        // <summary>
        // LinkedIn
        // </summary>
        LinkedIn = 754400002,
        
        // <summary>
        // XING
        // </summary>
        XING = 754400003,
        
        // <summary>
        // Konnects
        // </summary>
        Konnects = 754400004,
        
        // <summary>
        // Myspace
        // </summary>
        Myspace = 754400005,
    }
}
