//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // The unit of time for notice of a change in employment provided by the worker  Example:  Day or week
    // </summary>
    public enum cdm_WorkerUnitofNotice {
        
        // <summary>
        // Month
        // </summary>
        Month = 754400000,
        
        // <summary>
        // Week
        // </summary>
        Week = 754400001,
    }
}
