//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // The status of the worker  Example: Active, Inactive
    // </summary>
    public enum cdm_Status {
        
        // <summary>
        // Active
        // </summary>
        Active = 754400000,
        
        // <summary>
        // Inactive
        // </summary>
        Inactive = 754400001,
    }
}
