//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmWebApiEarlyBoundGenerator {
    
    
    // <summary>
    // The gender of the worker
    // </summary>
    public enum cdm_Gender {
        
        // <summary>
        // Male
        // </summary>
        Male = 754400000,
        
        // <summary>
        // Female
        // </summary>
        Female = 754400001,
        
        // <summary>
        // Not Specified
        // </summary>
        Not_Specified = 754400002,
        
        // <summary>
        // Non-specific
        // </summary>
        Nonspecific = 754400003,
    }
}
